/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface CategoryResponse
 */
export interface CategoryResponse {
  /**
   *
   * @type {number}
   * @memberof CategoryResponse
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof CategoryResponse
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof CategoryResponse
   */
  categoryGroupId?: number;
  /**
   *
   * @type {string}
   * @memberof CategoryResponse
   */
  categoryGroupName?: string;
}

/**
 * Check if a given object implements the CategoryResponse interface.
 */
export function instanceOfCategoryResponse(
  value: object
): value is CategoryResponse {
  return true;
}

export function CategoryResponseFromJSON(json: any): CategoryResponse {
  return CategoryResponseFromJSONTyped(json, false);
}

export function CategoryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CategoryResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    categoryGroupId:
      json['categoryGroupId'] == null ? undefined : json['categoryGroupId'],
    categoryGroupName:
      json['categoryGroupName'] == null ? undefined : json['categoryGroupName'],
  };
}

export function CategoryResponseToJSON(json: any): CategoryResponse {
  return CategoryResponseToJSONTyped(json, false);
}

export function CategoryResponseToJSONTyped(
  value?: CategoryResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    categoryGroupId: value['categoryGroupId'],
    categoryGroupName: value['categoryGroupName'],
  };
}
