/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface CategoryGroupResponse
 */
export interface CategoryGroupResponse {
  /**
   *
   * @type {number}
   * @memberof CategoryGroupResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof CategoryGroupResponse
   */
  name?: string;
}

/**
 * Check if a given object implements the CategoryGroupResponse interface.
 */
export function instanceOfCategoryGroupResponse(
  value: object
): value is CategoryGroupResponse {
  return true;
}

export function CategoryGroupResponseFromJSON(
  json: any
): CategoryGroupResponse {
  return CategoryGroupResponseFromJSONTyped(json, false);
}

export function CategoryGroupResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CategoryGroupResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
  };
}

export function CategoryGroupResponseToJSON(json: any): CategoryGroupResponse {
  return CategoryGroupResponseToJSONTyped(json, false);
}

export function CategoryGroupResponseToJSONTyped(
  value?: CategoryGroupResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
  };
}
