/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassifyPostsRequest
 */
export interface ClassifyPostsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassifyPostsRequest
     */
    postIds: Array<string>;
}

/**
 * Check if a given object implements the ClassifyPostsRequest interface.
 */
export function instanceOfClassifyPostsRequest(value: object): value is ClassifyPostsRequest {
    if (!('postIds' in value) || value['postIds'] === undefined) return false;
    return true;
}

export function ClassifyPostsRequestFromJSON(json: any): ClassifyPostsRequest {
    return ClassifyPostsRequestFromJSONTyped(json, false);
}

export function ClassifyPostsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassifyPostsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'postIds': json['postIds'],
    };
}

export function ClassifyPostsRequestToJSON(json: any): ClassifyPostsRequest {
    return ClassifyPostsRequestToJSONTyped(json, false);
}

export function ClassifyPostsRequestToJSONTyped(value?: ClassifyPostsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postIds': value['postIds'],
    };
}

