/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassifyPostsAcceptedResponse
 */
export interface ClassifyPostsAcceptedResponse {
    /**
     * 
     * @type {string}
     * @memberof ClassifyPostsAcceptedResponse
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof ClassifyPostsAcceptedResponse
     */
    requested?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassifyPostsAcceptedResponse
     */
    postIds?: Array<string>;
}

/**
 * Check if a given object implements the ClassifyPostsAcceptedResponse interface.
 */
export function instanceOfClassifyPostsAcceptedResponse(value: object): value is ClassifyPostsAcceptedResponse {
    return true;
}

export function ClassifyPostsAcceptedResponseFromJSON(json: any): ClassifyPostsAcceptedResponse {
    return ClassifyPostsAcceptedResponseFromJSONTyped(json, false);
}

export function ClassifyPostsAcceptedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassifyPostsAcceptedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'requested': json['requested'] == null ? undefined : json['requested'],
        'postIds': json['postIds'] == null ? undefined : json['postIds'],
    };
}

export function ClassifyPostsAcceptedResponseToJSON(json: any): ClassifyPostsAcceptedResponse {
    return ClassifyPostsAcceptedResponseToJSONTyped(json, false);
}

export function ClassifyPostsAcceptedResponseToJSONTyped(value?: ClassifyPostsAcceptedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'requested': value['requested'],
        'postIds': value['postIds'],
    };
}

