/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface CreateCategoryRequest
 */
export interface CreateCategoryRequest {
  /**
   *
   * @type {string}
   * @memberof CreateCategoryRequest
   */
  categoryGroupId: string;
  /**
   *
   * @type {string}
   * @memberof CreateCategoryRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateCategoryRequest
   */
  slug: string;
  /**
   *
   * @type {string}
   * @memberof CreateCategoryRequest
   */
  description: string;
}

/**
 * Check if a given object implements the CreateCategoryRequest interface.
 */
export function instanceOfCreateCategoryRequest(
  value: object
): value is CreateCategoryRequest {
  if (!('categoryGroupId' in value) || value['categoryGroupId'] === undefined)
    return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('slug' in value) || value['slug'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined)
    return false;
  return true;
}

export function CreateCategoryRequestFromJSON(
  json: any
): CreateCategoryRequest {
  return CreateCategoryRequestFromJSONTyped(json, false);
}

export function CreateCategoryRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateCategoryRequest {
  if (json == null) {
    return json;
  }
  return {
    categoryGroupId: json['categoryGroupId'],
    name: json['name'],
    slug: json['slug'],
    description: json['description'],
  };
}

export function CreateCategoryRequestToJSON(json: any): CreateCategoryRequest {
  return CreateCategoryRequestToJSONTyped(json, false);
}

export function CreateCategoryRequestToJSONTyped(
  value?: CreateCategoryRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    categoryGroupId: value['categoryGroupId'],
    name: value['name'],
    slug: value['slug'],
    description: value['description'],
  };
}
