/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface CreateFeedbackRequest
 */
export interface CreateFeedbackRequest {
  /**
   * BUG: 오류·장애 신고, CONTENT: 콘텐츠 관련 의견, FEATURE: 신규 기능 제안, UX: 사용성·화면 개선, ETC: 기타
   * @type {CreateFeedbackRequestCategoryEnum}
   * @memberof CreateFeedbackRequest
   */
  category: CreateFeedbackRequestCategoryEnum;
  /**
   *
   * @type {string}
   * @memberof CreateFeedbackRequest
   */
  content: string;
}

/**
 * @export
 */
export const CreateFeedbackRequestCategoryEnum = {
  Bug: 'BUG',
  Content: 'CONTENT',
  Feature: 'FEATURE',
  Ux: 'UX',
  Etc: 'ETC',
} as const;
export type CreateFeedbackRequestCategoryEnum =
  (typeof CreateFeedbackRequestCategoryEnum)[keyof typeof CreateFeedbackRequestCategoryEnum];

/**
 * Check if a given object implements the CreateFeedbackRequest interface.
 */
export function instanceOfCreateFeedbackRequest(
  value: object
): value is CreateFeedbackRequest {
  if (!('category' in value) || value['category'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function CreateFeedbackRequestFromJSON(
  json: any
): CreateFeedbackRequest {
  return CreateFeedbackRequestFromJSONTyped(json, false);
}

export function CreateFeedbackRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateFeedbackRequest {
  if (json == null) {
    return json;
  }
  return {
    category: json['category'],
    content: json['content'],
  };
}

export function CreateFeedbackRequestToJSON(json: any): CreateFeedbackRequest {
  return CreateFeedbackRequestToJSONTyped(json, false);
}

export function CreateFeedbackRequestToJSONTyped(
  value?: CreateFeedbackRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    category: value['category'],
    content: value['content'],
  };
}
