/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface CreateCategoryGroupRequest
 */
export interface CreateCategoryGroupRequest {
  /**
   *
   * @type {string}
   * @memberof CreateCategoryGroupRequest
   */
  name: string;
}

/**
 * Check if a given object implements the CreateCategoryGroupRequest interface.
 */
export function instanceOfCreateCategoryGroupRequest(
  value: object
): value is CreateCategoryGroupRequest {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CreateCategoryGroupRequestFromJSON(
  json: any
): CreateCategoryGroupRequest {
  return CreateCategoryGroupRequestFromJSONTyped(json, false);
}

export function CreateCategoryGroupRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateCategoryGroupRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function CreateCategoryGroupRequestToJSON(
  json: any
): CreateCategoryGroupRequest {
  return CreateCategoryGroupRequestToJSONTyped(json, false);
}

export function CreateCategoryGroupRequestToJSONTyped(
  value?: CreateCategoryGroupRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
