/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface FeedbackResponse
 */
export interface FeedbackResponse {
  /**
   *
   * @type {number}
   * @memberof FeedbackResponse
   */
  id?: number;
  /**
   *
   * @type {FeedbackResponseCategoryEnum}
   * @memberof FeedbackResponse
   */
  category?: FeedbackResponseCategoryEnum;
  /**
   *
   * @type {string}
   * @memberof FeedbackResponse
   */
  content?: string;
  /**
   *
   * @type {Date}
   * @memberof FeedbackResponse
   */
  createdAt?: Date;
}

/**
 * @export
 */
export const FeedbackResponseCategoryEnum = {
  Bug: 'BUG',
  Content: 'CONTENT',
  Feature: 'FEATURE',
  Ux: 'UX',
  Etc: 'ETC',
} as const;
export type FeedbackResponseCategoryEnum =
  (typeof FeedbackResponseCategoryEnum)[keyof typeof FeedbackResponseCategoryEnum];

/**
 * Check if a given object implements the FeedbackResponse interface.
 */
export function instanceOfFeedbackResponse(
  value: object
): value is FeedbackResponse {
  return true;
}

export function FeedbackResponseFromJSON(json: any): FeedbackResponse {
  return FeedbackResponseFromJSONTyped(json, false);
}

export function FeedbackResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FeedbackResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    category: json['category'] == null ? undefined : json['category'],
    content: json['content'] == null ? undefined : json['content'],
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
  };
}

export function FeedbackResponseToJSON(json: any): FeedbackResponse {
  return FeedbackResponseToJSONTyped(json, false);
}

export function FeedbackResponseToJSONTyped(
  value?: FeedbackResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    category: value['category'],
    content: value['content'],
    createdAt:
      value['createdAt'] == null
        ? value['createdAt']
        : value['createdAt'].toISOString(),
  };
}
