/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostCategoryResponse } from './PostCategoryResponse';
import {
  PostCategoryResponseFromJSON,
  PostCategoryResponseFromJSONTyped,
  PostCategoryResponseToJSON,
  PostCategoryResponseToJSONTyped,
} from './PostCategoryResponse';

/**
 *
 * @export
 * @interface PostResponse
 */
export interface PostResponse {
  /**
   *
   * @type {number}
   * @memberof PostResponse
   */
  postId?: number;
  /**
   *
   * @type {string}
   * @memberof PostResponse
   */
  title?: string;
  /**
   *
   * @type {Date}
   * @memberof PostResponse
   */
  pubDate?: Date;
  /**
   *
   * @type {string}
   * @memberof PostResponse
   */
  thumbnail?: string;
  /**
   *
   * @type {string}
   * @memberof PostResponse
   */
  url?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof PostResponse
   */
  tags?: Array<string>;
  /**
   *
   * @type {Array<PostCategoryResponse>}
   * @memberof PostResponse
   */
  categories?: Array<PostCategoryResponse>;
  /**
   *
   * @type {string}
   * @memberof PostResponse
   */
  sourceSiteName?: string;
  /**
   *
   * @type {PostResponseLanguageEnum}
   * @memberof PostResponse
   */
  language?: PostResponseLanguageEnum;
}

/**
 * @export
 */
export const PostResponseLanguageEnum = {
  Ko: 'KO',
  En: 'EN',
} as const;
export type PostResponseLanguageEnum =
  (typeof PostResponseLanguageEnum)[keyof typeof PostResponseLanguageEnum];

/**
 * Check if a given object implements the PostResponse interface.
 */
export function instanceOfPostResponse(value: object): value is PostResponse {
  return true;
}

export function PostResponseFromJSON(json: any): PostResponse {
  return PostResponseFromJSONTyped(json, false);
}

export function PostResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostResponse {
  if (json == null) {
    return json;
  }
  return {
    postId: json['postId'] == null ? undefined : json['postId'],
    title: json['title'] == null ? undefined : json['title'],
    pubDate: json['pubDate'] == null ? undefined : new Date(json['pubDate']),
    thumbnail: json['thumbnail'] == null ? undefined : json['thumbnail'],
    url: json['url'] == null ? undefined : json['url'],
    tags: json['tags'] == null ? undefined : json['tags'],
    categories:
      json['categories'] == null
        ? undefined
        : (json['categories'] as Array<any>).map(PostCategoryResponseFromJSON),
    sourceSiteName:
      json['sourceSiteName'] == null ? undefined : json['sourceSiteName'],
    language: json['language'] == null ? undefined : json['language'],
  };
}

export function PostResponseToJSON(json: any): PostResponse {
  return PostResponseToJSONTyped(json, false);
}

export function PostResponseToJSONTyped(
  value?: PostResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    postId: value['postId'],
    title: value['title'],
    pubDate:
      value['pubDate'] == null
        ? value['pubDate']
        : value['pubDate'].toISOString(),
    thumbnail: value['thumbnail'],
    url: value['url'],
    tags: value['tags'],
    categories:
      value['categories'] == null
        ? undefined
        : (value['categories'] as Array<any>).map(PostCategoryResponseToJSON),
    sourceSiteName: value['sourceSiteName'],
    language: value['language'],
  };
}
