/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface PostCategoryResponse
 */
export interface PostCategoryResponse {
  /**
   *
   * @type {string}
   * @memberof PostCategoryResponse
   */
  groupName?: string;
  /**
   *
   * @type {string}
   * @memberof PostCategoryResponse
   */
  categoryName?: string;
}

/**
 * Check if a given object implements the PostCategoryResponse interface.
 */
export function instanceOfPostCategoryResponse(
  value: object
): value is PostCategoryResponse {
  return true;
}

export function PostCategoryResponseFromJSON(json: any): PostCategoryResponse {
  return PostCategoryResponseFromJSONTyped(json, false);
}

export function PostCategoryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostCategoryResponse {
  if (json == null) {
    return json;
  }
  return {
    groupName: json['groupName'] == null ? undefined : json['groupName'],
    categoryName:
      json['categoryName'] == null ? undefined : json['categoryName'],
  };
}

export function PostCategoryResponseToJSON(json: any): PostCategoryResponse {
  return PostCategoryResponseToJSONTyped(json, false);
}

export function PostCategoryResponseToJSONTyped(
  value?: PostCategoryResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    groupName: value['groupName'],
    categoryName: value['categoryName'],
  };
}
