/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostResponse } from './PostResponse';
import {
  PostResponseFromJSON,
  PostResponseFromJSONTyped,
  PostResponseToJSON,
  PostResponseToJSONTyped,
} from './PostResponse';

/**
 *
 * @export
 * @interface PostResponseList
 */
export interface PostResponseList {
  /**
   *
   * @type {Array<PostResponse>}
   * @memberof PostResponseList
   */
  posts?: Array<PostResponse>;
  /**
   *
   * @type {boolean}
   * @memberof PostResponseList
   */
  hasNext?: boolean;
  /**
   *
   * @type {number}
   * @memberof PostResponseList
   */
  nextPostId?: number;
}

/**
 * Check if a given object implements the PostResponseList interface.
 */
export function instanceOfPostResponseList(
  value: object
): value is PostResponseList {
  return true;
}

export function PostResponseListFromJSON(json: any): PostResponseList {
  return PostResponseListFromJSONTyped(json, false);
}

export function PostResponseListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostResponseList {
  if (json == null) {
    return json;
  }
  return {
    posts:
      json['posts'] == null
        ? undefined
        : (json['posts'] as Array<any>).map(PostResponseFromJSON),
    hasNext: json['hasNext'] == null ? undefined : json['hasNext'],
    nextPostId: json['nextPostId'] == null ? undefined : json['nextPostId'],
  };
}

export function PostResponseListToJSON(json: any): PostResponseList {
  return PostResponseListToJSONTyped(json, false);
}

export function PostResponseListToJSONTyped(
  value?: PostResponseList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    posts:
      value['posts'] == null
        ? undefined
        : (value['posts'] as Array<any>).map(PostResponseToJSON),
    hasNext: value['hasNext'],
    nextPostId: value['nextPostId'],
  };
}
