/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface PostSearchCondition
 */
export interface PostSearchCondition {
  /**
   *
   * @type {string}
   * @memberof PostSearchCondition
   */
  keyword?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof PostSearchCondition
   */
  categoryIds?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof PostSearchCondition
   */
  sourceSiteName?: string;
}

/**
 * Check if a given object implements the PostSearchCondition interface.
 */
export function instanceOfPostSearchCondition(
  value: object
): value is PostSearchCondition {
  return true;
}

export function PostSearchConditionFromJSON(json: any): PostSearchCondition {
  return PostSearchConditionFromJSONTyped(json, false);
}

export function PostSearchConditionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostSearchCondition {
  if (json == null) {
    return json;
  }
  return {
    keyword: json['keyword'] == null ? undefined : json['keyword'],
    categoryIds: json['categoryIds'] == null ? undefined : json['categoryIds'],
    sourceSiteName:
      json['sourceSiteName'] == null ? undefined : json['sourceSiteName'],
  };
}

export function PostSearchConditionToJSON(json: any): PostSearchCondition {
  return PostSearchConditionToJSONTyped(json, false);
}

export function PostSearchConditionToJSONTyped(
  value?: PostSearchCondition | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    keyword: value['keyword'],
    categoryIds: value['categoryIds'],
    sourceSiteName: value['sourceSiteName'],
  };
}
