/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface UpdateCategoryGroupRequest
 */
export interface UpdateCategoryGroupRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateCategoryGroupRequest
   */
  name: string;
}

/**
 * Check if a given object implements the UpdateCategoryGroupRequest interface.
 */
export function instanceOfUpdateCategoryGroupRequest(
  value: object
): value is UpdateCategoryGroupRequest {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function UpdateCategoryGroupRequestFromJSON(
  json: any
): UpdateCategoryGroupRequest {
  return UpdateCategoryGroupRequestFromJSONTyped(json, false);
}

export function UpdateCategoryGroupRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateCategoryGroupRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function UpdateCategoryGroupRequestToJSON(
  json: any
): UpdateCategoryGroupRequest {
  return UpdateCategoryGroupRequestToJSONTyped(json, false);
}

export function UpdateCategoryGroupRequestToJSONTyped(
  value?: UpdateCategoryGroupRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
