/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface UpdateCategoryRequest
 */
export interface UpdateCategoryRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateCategoryRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UpdateCategoryRequest
   */
  slug: string;
  /**
   *
   * @type {string}
   * @memberof UpdateCategoryRequest
   */
  description: string;
}

/**
 * Check if a given object implements the UpdateCategoryRequest interface.
 */
export function instanceOfUpdateCategoryRequest(
  value: object
): value is UpdateCategoryRequest {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('slug' in value) || value['slug'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined)
    return false;
  return true;
}

export function UpdateCategoryRequestFromJSON(
  json: any
): UpdateCategoryRequest {
  return UpdateCategoryRequestFromJSONTyped(json, false);
}

export function UpdateCategoryRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateCategoryRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    slug: json['slug'],
    description: json['description'],
  };
}

export function UpdateCategoryRequestToJSON(json: any): UpdateCategoryRequest {
  return UpdateCategoryRequestToJSONTyped(json, false);
}

export function UpdateCategoryRequestToJSONTyped(
  value?: UpdateCategoryRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    slug: value['slug'],
    description: value['description'],
  };
}
