/* tslint:disable */
/* eslint-disable */
/**
 * TechGather API
 * API 리스트
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 *
 * @export
 * @interface UpdatePostsRequest
 */
export interface UpdatePostsRequest {
  /**
   *
   * @type {Array<string>}
   * @memberof UpdatePostsRequest
   */
  postIds?: Array<string>;
  /**
   *
   * @type {UpdatePostsRequestStatusEnum}
   * @memberof UpdatePostsRequest
   */
  status?: UpdatePostsRequestStatusEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof UpdatePostsRequest
   */
  categoryIds?: Array<string>;
}

/**
 * @export
 */
export const UpdatePostsRequestStatusEnum = {
  Discarded: 'DISCARDED',
  NotPublished: 'NOT_PUBLISHED',
  Published: 'PUBLISHED',
  OnHold: 'ON_HOLD',
} as const;
export type UpdatePostsRequestStatusEnum =
  (typeof UpdatePostsRequestStatusEnum)[keyof typeof UpdatePostsRequestStatusEnum];

/**
 * Check if a given object implements the UpdatePostsRequest interface.
 */
export function instanceOfUpdatePostsRequest(
  value: object
): value is UpdatePostsRequest {
  return true;
}

export function UpdatePostsRequestFromJSON(json: any): UpdatePostsRequest {
  return UpdatePostsRequestFromJSONTyped(json, false);
}

export function UpdatePostsRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdatePostsRequest {
  if (json == null) {
    return json;
  }
  return {
    postIds: json['postIds'] == null ? undefined : json['postIds'],
    status: json['status'] == null ? undefined : json['status'],
    categoryIds: json['categoryIds'] == null ? undefined : json['categoryIds'],
  };
}

export function UpdatePostsRequestToJSON(json: any): UpdatePostsRequest {
  return UpdatePostsRequestToJSONTyped(json, false);
}

export function UpdatePostsRequestToJSONTyped(
  value?: UpdatePostsRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    postIds: value['postIds'],
    status: value['status'],
    categoryIds: value['categoryIds'],
  };
}
